fun main(){
  herecias()


}
private  fun herecias(){

  var Rosa1 = ClaseRosa (1, "Rosa china", "Blanco")
  var Girasol1 = ClaseGirasol (1, "Girasol grande", "Amarillo", "Pipas XL saladas")
  var claveles1 = claveles (1, "Clavel", "Azul")
  var Amapola1 = Amapola (1, " Amapola silvestre", "Rojo")
  var Petunias1 = Petunias (1, "Petunia", "Naranja")
  var Calendulas1 = Calendulas (1, "Marigold", "Verde")
  var azucar1 = azucar("Azucar","Dulce","Blanco aunque puedo ser Marron")
  var canela1 = canela("Canela","Dulce y Leñoso","Canela")
  var curcuma1 = curcuma("Curcuma","Suave","Amarillo Intenso")
  var Lavanda1 = Lavanda (2, "Lavanda", "Lavanda")
  var Petunia1 = Petunia (2, "Petunia", "Rosa")
  var Shito1 = Shito (3, "Shito", "Rojo","Soy el bonsáis más pequeño que existe, y no soy nada habitualel. Me suelen plantar con semillas en contenedores de pequeño tamaño, y no suelo tener más de dos ramas.")
  var Cliente1 = Cliente ("Maria", "28", "Las Rosas")


  println("Presentaciones de las flores de la Floristeria Marti:")
  println("....................................................")
  println(" ")
  println("Hola buenos dias empiezo ,yo soy ${Rosa1.NombreComun} y mi color es ${Rosa1.Color}")
  Rosa1.crecer()
  println("Girasol te toca")
  println(" ")
  println("Yo soy ${Girasol1.NombreComun} y mi color es ${Girasol1.Color}")
  Girasol1.crecer()
  Girasol1.destino()
  println("Clavel quieres seguir tu?")
  println(" ")
  println("Yo soy ${claveles1.NombreComun} y mi color es ${claveles1.Color}")
  claveles1.crecer()
  println("Amapola bonita ilustranos")
  println(" ")
  println("Gracias clavel")
  println("Yo soy ${Amapola1.NombreComun} y mi color es ${Amapola1.Color}")
  Amapola1.crecer()
  println("Amiga petunia porfavor")
  println(" ")
  println("Soy ${Petunias1.NombreComun} y mi color es ${Petunias1.Color}")
  Petunias1.crecer()
  println("Calendula solo quedas tu sorprendenos")
  println(" ")
  println("Yo soy ${Calendulas1.NombreComun} y mi color es ${Calendulas1.Color}")
  Calendulas1.crecer()
  println(" ")
  println(" En la Floristeria Marti tambien se venden condimentos. Adelante podeis empezar:")
  println(".................................................................................")
  println(" ")
  println(" Hola buenos dias empiezo ,yo soy ${azucar1.Nombre}, mi sabor es ${azucar1.Sabor} y mi color es ${azucar1.Color}")
  azucar1.crecer()
  println(" Canela muestranos")
  println(" ")
  println("Yo soy ${canela1.Nombre}, mi sabor es ${canela1.Sabor} y mi color es ${canela1.Color}")
  canela1.crecer()
  println("Curcuma de nosotros solo quedas tu algo que decir?")
  println(" ")
  println("Claro canela, yo soy ${curcuma1.Nombre}, mi sabor es ${curcuma1.Sabor} y mi color es ${curcuma1.Color}")
  curcuma1.crecer()


  println(" ")
  println("No solo existen las flores normales si no que ademas existen otro tipo de flores son las Ornamentales:")
  println(".................................................................................")
  println(" ")
  println(" Hola buenos dias,yo soy ${Lavanda1.NombreComun} y mi color es ${Lavanda1.Color}")
  Lavanda1.crecer()
  println("Petunia hablanos un poco de ti")
  println(" ")
  println("Yo soy ${Petunia1.NombreComun}y mi color es ${Petunia1.Color}")
  Petunia1.crecer()
  println(" ")


  println("Y aqui os Presento a nuestro Bonsai")
  println(".................................................................................")
  println(" ")
  println(" Hola buenos dias,yo soy ${Shito1.NombreComun} y mi color es ${Shito1.Tipo}")
  Shito1.destino()
  println(" ")

  println("Buenos dias que desea:")
  println(".................................................................................")
  println(" ")
  println(" Hola buenos dias,yo soy ${Cliente1.Nombre} y quiero comprar  ${Cliente1.Compra}")

}